### ISSUE TITLE
Mobile browser safe areas / viewport heights

### ISSUE THREAD

**Issue by MedliPlays** [ConnectNowUK/hedgehog-css#2]
![Screenshot_20210614-102728](https://user-images.githubusercontent.com/7777823/121871821-76175e80-ccfc-11eb-8455-1e8d814aadf9.jpg)

See screenshot - browser menu/navbar sitting over the UI, as well as Chrome's horrible-ass tab grouping garbage they're shoehorning in.

Basically a SafeArea thing if we're talkin' native.

**Comment by MedliPlays** [comment]
Android 10

**Comment by mwargan** [comment]
@ashcarr92 Damn, I don't have a way to re-create the issue. Know of any emulators?

**Comment by MedliPlays** [comment]
Yeah just use Android Studio it has one built in - used it all the time in my old job on a MacBook Pro

**Comment by MedliPlays** [comment]
Replicated locally on android 10 and 11.

I genuinely think you just have to scroll down. No joke.
Seems this is "normal" behaviour for Chrome which is a fuckin' joke. Chrome's 100VH is **always** the full height of the viewport **regardless** of the manu or tab bars, and it doesn't adapt. Firefox and safari both do; 100vh on those browsers is the gap between the toolbar and the bottom edge of the viewport. 
https://stackoverflow.com/questions/52848856/100vh-height-when-address-bar-is-shown-chrome-mobile


What pisses me off even more is that it appears their own dev tools doesn't recognise that the stupid tab group is actually a UI element - note no checkerboard on the bottom of the inspector.
![image](https://user-images.githubusercontent.com/7777823/122085033-40f13600-cdfa-11eb-83a1-47c0c8093f9e.png)



Assked Nick to verify scrolling behaviour on physical device

**Comment by MedliPlays** [comment]
![ezgif-2-f329d8dfbe54](https://user-images.githubusercontent.com/7777823/122086001-31262180-cdfb-11eb-8429-e0d138dc0ee5.gif)

**Comment by mwargan** [comment]
Possibly related? https://stackoverflow.com/a/59020698/7410951, although I do think we've tried the second suggested answer: https://stackoverflow.com/a/58048556/7410951

**Comment by MedliPlays** [comment]
See Nick's phone's behaviour, his address bar on V2 doesn't shrink at all, the bottom input is stuck off screen . Friggin weird considering we're supposedly on the identical version of Chrome... Oh Android how I love your quirks.

The most annoying thing here is replicating the issue, I have all sorts of ideas to try but how do I verify them except asking Nick 

https://user-images.githubusercontent.com/7777823/122366836-d3f1b380-cf53-11eb-8bce-b038ae3b0a14.mp4


https://user-images.githubusercontent.com/7777823/122366844-d48a4a00-cf53-11eb-8747-755077002f4e.mp4

**Comment by ashcarr92** [comment]
I'm a dumbass. My phone behaves exactly the same if there are enough messages to cause a scroll.

Fuckin' nooooooob.

**Comment by MedliPlays** [comment]
https://user-images.githubusercontent.com/7777823/122368642-6ba3d180-cf55-11eb-9825-933f327e5fa5.mp4

You know what - there's actually a related issue on iOS Safari. The viewport itself doesn't "scroll" so the address bad and toolbar never shrink to their smaller size, limiting the available space for the user to interact. 
Think this might actually need a rejig in more than just CSS

**Comment by ashcarr92** [comment]
https://user-images.githubusercontent.com/7777823/122368587-6050a600-cf55-11eb-97dc-9081cb035784.mp4

**Comment by mwargan** [comment]
Not an issue on iOS - expected behaviour with no known workarounds

**Comment by MedliPlays** [comment]
What? Loads of websites work just fine where when you scroll the browser's native UI elements fold away, with a sticky navbar or footer, which is exactly what we're looking at here. This actual page right here does it. I've managed to get Android to behave perfectly this way, though iOS is putting up a fight

**Comment by mwargan** [comment]
This is by design. Scrolling a whole document is different to having a scrollable container. Additionally, when bars hide, any input requires two taps vs one (the first re-opens those UI elements, only the second actually enters the input), therefore its best to keep them open to prevent the need for double tapping on inputs.

Long story short: when closed it would still open when tapping on inputs; the repeated opening and closing is way more annoying than just keeping it open.

Related: https://stackoverflow.com/q/21715917/7410951.

**Comment by MedliPlays** [comment]
I don't have to double tap and entering the input field doesn't cause the UI to reappear?

**Comment by mwargan** [comment]
The behaviour is different when you forcefully use "Hide Toolbar". A common example is Airbnb's bottom nav bar. This is a known issue for years now: https://apple.stackexchange.com/questions/130822/safari-ios-menu-bar-conflicts-with-buttons-in-lower-10-of-the-screen

I think at this point this has become an [xy-problem](https://xyproblem.info). The goal of this issue is to fix the height issues on older Android browsers, not to override system browser behaviour.

**Comment by mwargan** [comment]
Fixed inability to hide browser UI elements on Android upon a scroll down in the chat window: https://github.com/ConnectNowUK/hedgehog-css/commit/ef2ee27c65c2dfef1a4dff2f3f9014d5f3e7730d

**Comment by ashcarr92** [comment]
https://github.com/ConnectNowUK/hedgehog-css/commit/ef2ee27c65c2dfef1a4dff2f3f9014d5f3e7730d  doesn't really fix the issue - the input remains off screen until you scroll all the way down and then scroll _again_ against the "bounce"

https://user-images.githubusercontent.com/7777823/122546652-16d08b80-d027-11eb-8e06-864092f8235d.mp4

"Hide Toolbar?" I've changed a few CSS classes and now when I scroll down, the bars disappear, when I scroll up or tap the address bar, it reappears. That _is_ the default behaviour. Yes, there is a distinct difference between scrolling a container vs scrolling the viewport; that's why Android won't hide the UI automatically; the container is scrolling, not the viewport so it never hides them, and because of `vh` including the bars in the calculation, the bottom bar remains obscured.

We have two choices. Add `position: fixed` and `height: 100%` on the `main` element and that locks the UI bars open on both browsers, if that's what we want. Pretty easy, but due to z-indexing the sidebar needs its own close button. I've already done this as I also needed to do it for my other experimental solution to the problem. But why _wouldn't_ we want to UI bars to move out of the way? Look at this small form factor Android with the UI locked open vs closed.
![image](https://user-images.githubusercontent.com/7777823/122541563-a96e2c00-d021-11eb-8b03-f85d131c2bba.png)
That's a lot of screen space we're losing, no?

The videos you're seeing is a local instance where all I'm doing is scrolling up and down, I'm not "overriding" anything. Now yes, iOS is being a bitch where it sticks and you have to scroll twice, and sometimes the bars just point blank refuse to disappear and it behaves basically as it does now. Perhaps it isn't worth the battle.

The previous videos shows a single tap to enter the input without the UI reappearing, when this happened I was surprised as I'm aware of Safari's dumbass and boneheaded habit of opening the browser UI if you tap the lower area of the screen - my fave takeaway does it all the time as they have a floating lower navbar, just like our input bar. How I managed to get it to do this I don't know, because its now showing the UI on tap again.

**Comment by mwargan** [comment]
Issue tested and confirmed resolved by our native Androider, Nick :)
